# Generated by Django 2.1.7 on 2020-01-31 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('inspectors', models.CharField(max_length=150, verbose_name='考察人员')),
                ('location', models.CharField(max_length=150, verbose_name='地点')),
                ('content', simditor.fields.RichTextField(verbose_name='项目内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('publish_date', models.DateField(verbose_name='发布时间')),
                ('status', models.CharField(choices=[('0', '编辑完成'), ('1', '编辑中')], default='1', max_length=2, verbose_name='状态')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='提交者')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'ordering': ('create_time',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('abstract', models.CharField(max_length=300, verbose_name='摘要')),
                ('content', simditor.fields.RichTextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('publish_date', models.DateField(verbose_name='发布时间')),
                ('status', models.CharField(choices=[('0', '编辑完成'), ('1', '编辑中')], default='1', max_length=2, verbose_name='状态')),
                ('image', models.ImageField(upload_to='', verbose_name='新闻必须配图')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='提交者')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'ordering': ('create_time',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='分类名称')),
                ('create_time', models.TimeField(verbose_name='创建时间')),
                ('status', models.CharField(choices=[('0', '编辑完成'), ('1', '编辑中')], default='0', max_length=2, verbose_name='状态')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Slogan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('content', simditor.fields.RichTextField(verbose_name='内容')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='上传图片')),
            ],
            options={
                'verbose_name': '固定标语',
                'verbose_name_plural': '固定标语',
            },
        ),
    ]
